server:
  port: 8112
spring:
  application:
    name: dubbo-client
  cloud:
    nacos:
      service-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
dubbo:
  scan:
    base-packages: com.tyza66.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848